import { createContext, useContext, useEffect, useState } from 'react';

const LanguageContext = createContext(null);

const hindi = {
  Dashboard: 'डैशबोर्ड', Expenses: 'खर्चे', Income: 'आय', Budget: 'बजट', Savings: 'बचत', Reports: 'रिपोर्ट',
  Notifications: 'सूचनाएँ', Profile: 'प्रोफ़ाइल', Settings: 'सेटिंग्स', Overview: 'अवलोकन',
  'Welcome back, ': 'वापसी पर स्वागत है, ', User: 'उपयोगकर्ता', Logout: 'लॉग आउट',
  'Toggle menu': 'मेन्यू खोलें या बंद करें', 'Select language': 'भाषा चुनें', English: 'English', Hindi: 'हिन्दी',
  'Open full profile': 'पूरी प्रोफ़ाइल खोलें',
  'All rights reserved.': 'सर्वाधिकार सुरक्षित।', Privacy: 'गोपनीयता', Terms: 'नियम', Support: 'सहायता',
  'Expense workspace': 'खर्च कार्यक्षेत्र', 'Daily entries, period totals, and group settlement in one place.': 'रोज़ के खर्च, अवधि का कुल हिसाब और समूह का बँटवारा एक जगह।',
  'This week': 'इस सप्ताह', 'This month': 'इस महीने', 'Combined total': 'कुल खर्च', 'Personal and group expenses': 'व्यक्तिगत और समूह के खर्च',
  'Personal · ': 'व्यक्तिगत · ', ' entries': ' प्रविष्टियाँ', 'Daily expenses in this period': 'इस अवधि के रोज़मर्रा के खर्च',
  'Group · ': 'समूह · ', 'Shared expenses in this period': 'इस अवधि के साझा खर्च', 'Period totals are currently unavailable.': 'अवधि का हिसाब अभी उपलब्ध नहीं है।',
  'Day activity': 'दिन का हिसाब', 'Check what you spent on any previous date.': 'किसी भी पिछली तारीख का खर्च देखें।',
  'Previous week': 'पिछला सप्ताह', 'Next week': 'अगला सप्ताह', 'Selected week': 'चुना हुआ सप्ताह',
  'Weekly final account': 'साप्ताहिक अंतिम हिसाब', 'This week is final.': 'इस सप्ताह का हिसाब पूरा है।',
  'Week closes on Sunday: ': 'सप्ताह का हिसाब रविवार को पूरा होगा: ', 'Pending group payments': 'समूह का बाकी भुगतान',
  'No pending group payments for this week.': 'इस सप्ताह समूह का कोई भुगतान बाकी नहीं है।',
  'Payments stay pending until marked paid.': 'भुगतान होने पर चिह्नित करने तक रकम बाकी रहेगी।', owes: 'को देने हैं',
  'Previous day': 'पिछला दिन', 'Choose expense date': 'खर्च की तारीख चुनें', 'Next day': 'अगला दिन',
  'No personal or group expenses recorded for this date.': 'इस तारीख के लिए कोई व्यक्तिगत या समूह खर्च दर्ज नहीं है।',
  'View full record': 'पूरा रिकॉर्ड देखें', Personal: 'व्यक्तिगत', Group: 'समूह', 'Not specified': 'उल्लेख नहीं है',
  'Recorded by: ': ' · दर्ज किया: ', 'Date': 'तारीख', Description: 'विवरण', Category: 'श्रेणी', 'Payment method': 'भुगतान का तरीका',
  'Paid by': 'भुगतानकर्ता', 'Recorded by': 'दर्ज करने वाला', Amount: 'राशि', Created: 'दर्ज किया गया', 'Last updated': 'आखिरी बदलाव',
  'Total amount': 'कुल राशि', 'Participants and shares': 'सदस्य और उनका हिस्सा', 'Settlement records': 'हिसाब निपटान रिकॉर्ड',
  'No settlement required.': 'हिसाब बराबर है, भुगतान बाकी नहीं।', ' pays ': ' को भुगतान करें ', ' · ': ' · ',
  'Add daily expense': 'रोज़ का खर्च जोड़ें', 'Expense history': 'खर्च का इतिहास', 'Group & settlement': 'समूह और हिसाब',
  'expenses on ': ' खर्च · तारीख ', 'Total: ': 'कुल: ',
  'Daily Expense': 'रोज़ का खर्च', 'Track today’s spending': 'आज का खर्च दर्ज करें',
  'Personal expense ya group expense, dono yahin se add karein.': 'व्यक्तिगत या समूह का खर्च, दोनों यहीं जोड़ें।',
  'Add group expense': 'समूह का खर्च जोड़ें', Select: 'चुनें', 'Select category': 'श्रेणी चुनें',
  'Potato + Onion': 'आलू + प्याज़', 'Select who paid': 'भुगतानकर्ता चुनें', "Add person's name": 'व्यक्ति का नाम जोड़ें',
  'Add person': 'व्यक्ति जोड़ें', 'Payment Method': 'भुगतान का तरीका',
  'Saving...': 'सहेजा जा रहा है...', 'Add Expense': 'खर्च जोड़ें', 'Expense added successfully.': 'खर्च सफलतापूर्वक जोड़ा गया।',
  'Unable to save expense.': 'खर्च सहेजा नहीं जा सका।', 'Person added.': 'व्यक्ति जोड़ा गया।', 'Unable to add person.': 'व्यक्ति नहीं जोड़ा जा सका।',
  'Today’s Snapshot': 'आज का सारांश', 'Today’s total': 'आज का कुल खर्च', 'Monthly budget': 'मासिक बजट', Remaining: 'बाकी',
  'Expenses for ': 'इस तारीख के खर्च: ', 'No expenses recorded for this date.': 'इस तारीख के लिए कोई खर्च दर्ज नहीं है।',
  Payment: 'भुगतान',
  'Expense tracking': 'खर्च का हिसाब', 'Personal expenses ke saath group expenses bhi manage karein.': 'व्यक्तिगत और समूह के खर्च यहाँ संभालें।',
  'Add expense': 'खर्च जोड़ें', 'Create expense': 'खर्च दर्ज करें', 'Edit expense': 'खर्च संपादित करें',
  'Equal split settlement': 'बराबर हिस्से का हिसाब',
  'Payer-assigned expenses are split across all ': 'दर्ज किए गए खर्च सभी ',
  ' listed people, including anyone who paid nothing.': ' लोगों में बराबर बाँटे जाते हैं, जिन्होंने भुगतान नहीं किया वे भी शामिल हैं।',
  Person: 'व्यक्ति', Paid: 'भुगतान किया', 'Equal share': 'बराबर हिस्सा', Settlement: 'हिसाब', Actions: 'कार्रवाई',
  'Receives ': 'पाएँगे ', 'Owes ': 'देना है ', Settled: 'हिसाब बराबर', 'Who pays whom': 'कौन किसे भुगतान करेगा',
  'Everyone is settled. No payments are due.': 'सभी का हिसाब बराबर है। कोई भुगतान बाकी नहीं।',
  'Person who pays': 'भुगतान करने वाला', 'Person who receives': 'राशि पाने वाला', 'Delete this expense?': 'यह खर्च हटाएँ?',
  'Unable to load expenses. Please try again later.': 'खर्च लोड नहीं हो सके। कृपया बाद में फिर कोशिश करें।',
  'Delete ': 'हटाएँ ',
  'Shared money, made clear': 'साझा खर्च का साफ़ हिसाब', 'Group expenses': 'समूह के खर्च',
  'Split fairly, then see exactly who pays whom.': 'बराबर बाँटें और देखें कि किसे किसे कितना देना है।',
  'New shared expense': 'नया साझा खर्च', 'The payer is always treated as a participant.': 'भुगतानकर्ता भी समूह के सदस्यों में शामिल होगा।',
  'Expense title or description': 'खर्च का नाम या विवरण', Participants: 'सदस्य',
  'Select all (': 'सभी चुनें (', ' people included · each share is ': ' लोग शामिल · हर व्यक्ति का हिस्सा ',
  'Select all': 'सभी चुनें', 'Add group member': 'समूह का सदस्य जोड़ें', Add: 'जोड़ें', 'Select payer': 'भुगतानकर्ता चुनें',
  'Add another payer': 'एक और भुगतानकर्ता जोड़ें', 'Save group expense': 'समूह का खर्च सहेजें',
  'Category (optional)': 'श्रेणी (वैकल्पिक)', 'people included · each share is ': ' लोग शामिल · हर व्यक्ति का हिस्सा ',
  'Remove payer': 'भुगतानकर्ता हटाएँ', paid: 'ने भुगतान किया', share: 'हिस्सा', pay: 'भुगतान करें', receive: 'पाएँ',
  'Receives': 'पाएँगे', Owes: 'देना है',
  Pays: 'भुगतानकर्ता', 'Each row shows the exact payment needed to settle this expense.': 'हर पंक्ति में इस खर्च का बकाया भुगतान दिया गया है।',
  payment: 'भुगतान', payments: 'भुगतान', 'Everyone is settled. No payment is due.': 'सभी का हिसाब बराबर है। कोई भुगतान बाकी नहीं।',
  'Unable to load your group workspace.': 'समूह का पेज लोड नहीं हो सका।',
  'Unable to add group member.': 'समूह का सदस्य नहीं जोड़ा जा सका।',
  'Enter an amount greater than zero and select at least one participant.': 'शून्य से अधिक राशि दर्ज करें और कम से कम एक सदस्य चुनें।',
  'Payer amounts must add up to the total expense.': 'भुगतानकर्ताओं की राशियों का योग कुल खर्च के बराबर होना चाहिए।',
  'Group expense saved.': 'समूह का खर्च सहेजा गया।', 'Unable to save group expense.': 'समूह का खर्च सहेजा नहीं जा सका।',
  'Delete this group expense and its settlement records?': 'यह समूह खर्च और इसका हिसाब रिकॉर्ड हटाएँ?',
  'Loading group expenses...': 'समूह के खर्च लोड हो रहे हैं...', 'No shared expenses yet': 'अभी कोई साझा खर्च नहीं है',
  'Create one to see the settlement plan.': 'हिसाब योजना देखने के लिए साझा खर्च जोड़ें।',
  'Total expense': 'कुल खर्च', 'Per-person share': 'प्रति व्यक्ति हिस्सा',
  'Settlement history': 'हिसाब निपटान का इतिहास',
  'Settlements will appear here after a group expense is created.': 'समूह खर्च जोड़ने के बाद यहाँ भुगतान का रिकॉर्ड दिखेगा।',
  'Mark paid': 'भुगतान हुआ चिह्नित करें',
  Cash: 'नकद', Other: 'अन्य', 'Debit Card': 'डेबिट कार्ड', 'Credit Card': 'क्रेडिट कार्ड', Wallet: 'वॉलेट',
  'Net Banking': 'नेट बैंकिंग', 'No expenses found': 'कोई खर्च नहीं मिला',
  'Search expenses': 'खर्च खोजें', Newest: 'नए पहले', Oldest: 'पुराने पहले', 'Highest amount': 'सबसे बड़ी राशि', 'Lowest amount': 'सबसे छोटी राशि',
  'Loading expenses...': 'खर्च लोड हो रहे हैं...', 'Add your first expense to start tracking spending.': 'हिसाब शुरू करने के लिए पहला खर्च जोड़ें।',
  'Unable to delete expense.': 'खर्च हटाया नहीं जा सका।',
  ' expense on ': ' खर्च दिनांक ', ' expenses on ': ' खर्च दिनांक ', expense: 'खर्च', expenses: 'खर्च',
  'Spent': 'खर्च', 'Set budget': 'बजट तय करें', 'Budget amount': 'बजट की राशि',
  'Save monthly budget': 'मासिक बजट सहेजें', 'Category budgets': 'श्रेणी के बजट',
  'No category budget limits have been set yet.': 'अभी तक किसी श्रेणी की बजट सीमा तय नहीं है।',
  'Total category budget: ': 'श्रेणी के बजट का कुल: ', 'Unable to load budget data.': 'बजट डेटा लोड नहीं हो सका।',
  'Unable to save monthly budget.': 'मासिक बजट सहेजा नहीं जा सका।', Cashflow: 'आय-व्यय',
  'Add income': 'आय जोड़ें', 'Edit income': 'आय संपादित करें', 'Save income': 'आय सहेजें', 'Update income': 'आय अपडेट करें',
  'Search income': 'आय खोजें', 'Loading income...': 'आय लोड हो रही है...', 'No income records': 'आय का कोई रिकॉर्ड नहीं',
  'Create your first income source.': 'अपनी आय का पहला स्रोत दर्ज करें।', 'Income entry': 'आय प्रविष्टि',
  'Unable to load income records.': 'आय के रिकॉर्ड लोड नहीं हो सके।', 'Unable to save income record.': 'आय का रिकॉर्ड सहेजा नहीं जा सका।',
  'Delete this income record?': 'आय का यह रिकॉर्ड हटाएँ?', 'Unable to delete income record.': 'आय का रिकॉर्ड हटाया नहीं जा सका।',
  'Build your financial cushion': 'अपनी बचत मज़बूत करें', 'Emergency fund goal': 'आपातकालीन निधि का लक्ष्य',
  Saved: 'बचत हुई', Target: 'लक्ष्य', 'No savings goals yet.': 'अभी कोई बचत लक्ष्य नहीं है।',
  'Reports & insights': 'रिपोर्ट और जानकारी', 'Monthly spend': 'मासिक खर्च', 'Savings rate': 'बचत दर',
  'Biggest category': 'सबसे बड़ी खर्च श्रेणी', 'Budget left': 'बाकी बजट', 'No data': 'कोई डेटा नहीं',
  'Expense trend': 'खर्च का रुझान', 'No trend data available yet.': 'अभी खर्च के रुझान का डेटा उपलब्ध नहीं है।',
  'Smart suggestions': 'सुझाव', 'is your top spending category at ': ' में आपका सबसे अधिक खर्च हुआ: ',
  'Add a few expenses to generate smarter spending insights.': 'खर्च के बेहतर सुझाव पाने के लिए कुछ खर्च दर्ज करें।',
  'Current balance: ': 'मौजूदा बैलेंस: ', 'Budget remaining: ': 'बजट में बाकी: ',
  'Member since': 'सदस्य बने', "Person's group": 'समूह', Status: 'स्थिति', Active: 'सक्रिय',
  Security: 'सुरक्षा', 'Password changes are managed securely through the authenticated reset flow.': 'पासवर्ड सुरक्षित रीसेट प्रक्रिया से बदला जाता है।',
  'Two-step verification': 'दो-चरणीय सत्यापन', Enabled: 'चालू', 'N/A': 'उपलब्ध नहीं',
  Account: 'खाता', 'Profile settings': 'प्रोफ़ाइल सेटिंग्स', Name: 'नाम', Email: 'ईमेल',
  'Not available': 'उपलब्ध नहीं', Preferences: 'प्राथमिकताएँ',
  'Currency format: INR': 'मुद्रा प्रारूप: INR', 'Default view: Dashboard': 'डिफ़ॉल्ट पेज: डैशबोर्ड',
  'Budget reminders: Enabled': 'बजट रिमाइंडर: चालू', 'Two-factor auth: Coming soon': 'दो-चरणीय सुरक्षा: जल्द आ रही है',
  Activity: 'गतिविधि', 'Loading notifications...': 'सूचनाएँ लोड हो रही हैं...', 'No notifications yet': 'अभी कोई सूचना नहीं',
  'Your financial activity will appear here.': 'आपकी वित्तीय गतिविधि यहाँ दिखाई देगी।', 'Mark read': 'पढ़ा हुआ चिह्नित करें',
  'Your financial overview': 'आपके पैसों का सारांश', 'Shared group view': 'साझा समूह का हिसाब',
  'Your group settlement': 'आपके समूह का हिसाब', 'Open group expenses': 'समूह के खर्च खोलें',
  'Total group expenses': 'समूह का कुल खर्च', 'Your contribution': 'आपका योगदान', 'Your share': 'आपका हिस्सा',
  'You need to pay': 'आपको देना है', 'You need to receive': 'आपको मिलने हैं', 'Net balance': 'बाकी हिसाब',
  'Available balance': 'उपलब्ध बैलेंस', 'Net total across all recorded income and expenses': 'दर्ज आय और खर्च के बाद कुल बैलेंस',
  'Total income': 'कुल आय', 'Total expenses': 'कुल खर्च', 'Spent this month': 'इस महीने अब तक का खर्च',
  used: 'इस्तेमाल', 'No budget set': 'बजट तय नहीं है', 'Over budget': 'बजट से अधिक', 'Spent today': 'आज का खर्च',
  'Income vs expenses': 'आय और खर्च', 'All recorded activity': 'सभी दर्ज गतिविधियाँ', 'Monthly trend': 'मासिक रुझान',
  'Income vs spending': 'आय और खर्च', 'View report': 'रिपोर्ट देखें', 'Recent activity': 'हाल की गतिविधि',
  'Your latest income and expenses': 'आपकी हाल की आय और खर्च', 'View all': 'सभी देखें',
  'No transactions yet': 'अभी कोई लेन-देन नहीं', 'Add your first expense to get started.': 'शुरू करने के लिए अपना पहला खर्च जोड़ें।',
  'Control your cashflow': 'अपने पैसों का हिसाब रखें', 'Track every rupee with clarity and confidence.': 'हर रुपये का हिसाब आसानी और भरोसे से रखें।',
  'Real-time budgets': 'तुरंत बजट अपडेट', 'Smart savings goals': 'बचत के लक्ष्य', 'Instant expense insights': 'खर्च की तुरंत जानकारी',
  'Sign in to your account': 'अपने खाते में लॉग इन करें', 'Email address': 'ईमेल पता', 'Enter your password': 'अपना पासवर्ड दर्ज करें',
  'Toggle password visibility': 'पासवर्ड दिखाएँ या छिपाएँ', 'Remember me': 'मुझे याद रखें', 'Forgot password?': 'पासवर्ड भूल गए?',
  'Signing in...': 'लॉग इन हो रहे हैं...', Login: 'लॉग इन', 'Don’t have an account?': 'खाता नहीं है?', 'Create one': 'खाता बनाएँ',
  'Login failed.': 'लॉग इन नहीं हो सका।', 'Get started': 'शुरू करें', 'Build a stronger financial future with smarter tracking.': 'बेहतर हिसाब से अपना आर्थिक भविष्य मज़बूत करें।',
  'Set monthly budgets': 'मासिक बजट तय करें', 'Monitor income and expenses': 'आय और खर्च देखें', 'Reach savings goals faster': 'बचत लक्ष्य जल्दी पाएँ',
  'New here?': 'यहाँ नए हैं?', 'Verify your email': 'ईमेल सत्यापित करें', 'Enter the six-digit code sent to': 'भेजा गया छह अंकों का कोड दर्ज करें:',
  'Email verification code': 'ईमेल सत्यापन कोड', 'Verifying...': 'सत्यापन हो रहा है...', 'Verify email': 'ईमेल सत्यापित करें',
  'Sending...': 'भेजा जा रहा है...', 'Resend verification code': 'सत्यापन कोड फिर भेजें', 'Full name': 'पूरा नाम',
  'Your full name': 'अपना पूरा नाम', Family: 'परिवार', Friends: 'दोस्त', Business: 'व्यवसाय', Team: 'टीम',
  'Create a strong password': 'मज़बूत पासवर्ड बनाएँ', 'Use at least 8 characters, including uppercase, numbers, and symbols.': 'कम से कम 8 अक्षर रखें, जिनमें बड़े अक्षर, अंक और चिह्न हों।',
  'Confirm password': 'पासवर्ड की पुष्टि करें', 'Confirm your password': 'पासवर्ड फिर दर्ज करें',
  'Toggle confirm password visibility': 'पुष्टि वाला पासवर्ड दिखाएँ या छिपाएँ', 'Creating account...': 'खाता बनाया जा रहा है...',
  'Create account': 'खाता बनाएँ', 'Already have an account?': 'पहले से खाता है?', Weak: 'कमज़ोर', Fair: 'ठीक', Good: 'अच्छा', Strong: 'मज़बूत',
  'Passwords do not match.': 'पासवर्ड मेल नहीं खाते।', 'Unable to verify the code.': 'कोड सत्यापित नहीं हो सका।',
  'Unable to resend the code. Please try again.': 'कोड फिर नहीं भेजा जा सका। कृपया दोबारा कोशिश करें।', 'Registration failed.': 'खाता नहीं बन सका।',
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('app_language') || 'en');

  useEffect(() => {
    localStorage.setItem('app_language', language);
    document.documentElement.lang = language === 'hi' ? 'hi' : 'en';
  }, [language]);

  const value = {
    language,
    setLanguage,
    t: (text) => language === 'hi' ? (hindi[text] ?? text) : text,
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}