# Generated by Django 5.1.1 on 2026-09-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Family', 'Family'), ('Friends', 'Friends'), ('Business', 'Business'), ('Team', 'Team')], default='Personal', max_length=50),
        ),
    ]
