# Generated by Django 5.1.1 on 2026-09-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Registration'), ('login', 'Login')], default='registration', max_length=20),
        ),
    ]
