# Generated by Django 5.1.1 on 2026-09-28 08:28

from django.conf import settings
from django.db import migrations, models


def add_default_categories(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    Category = apps.get_model("expenses", "Category")
    categories = [
        ("Grocery", "EXPENSE", "shopping-bag"),
        ("Vegetables", "EXPENSE", "carrot"),
        ("Fruits", "EXPENSE", "apple"),
        ("Snacks", "EXPENSE", "cookie"),
        ("Food", "EXPENSE", "utensils"),
        ("Rent", "EXPENSE", "house"),
        ("Electricity", "EXPENSE", "zap"),
        ("Transport", "EXPENSE", "car"),
        ("Shopping", "EXPENSE", "shopping-bag"),
        ("Medical", "EXPENSE", "heart-pulse"),
        ("Education", "EXPENSE", "book-open"),
        ("Entertainment", "EXPENSE", "clapperboard"),
        ("Bills", "EXPENSE", "wifi"),
        ("Other", "EXPENSE", "circle-ellipsis"),
        ("Milk & Dairy", "EXPENSE", "milk"),
        ("Petrol", "EXPENSE", "car"),
        ("Cleaning", "EXPENSE", "sparkles"),
        ("Internet", "EXPENSE", "wifi"),
        ("Salary", "INCOME", "wallet"),
        ("Freelancing", "INCOME", "briefcase"),
        ("Business", "INCOME", "building"),
        ("Bonus", "INCOME", "badge-percent"),
        ("Other income", "INCOME", "circle-plus"),
    ]
    database = schema_editor.connection.alias
    for user in User.objects.using(database).all().iterator():
        for name, category_type, icon in categories:
            Category.objects.using(database).get_or_create(
                user_id=user.pk,
                name=name,
                type=category_type,
                defaults={"icon": icon},
            )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_emailotp"),
        ('expenses', '0003_groupexpense_groupmember_groupexpenseparticipant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='income',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(add_default_categories, migrations.RunPython.noop),
    ]
